config/routes.rb
Rails.application.routes.draw do
  root :to => 'sessions#new'
  resources :favorites, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
    collection do
      post :confirm
      patch :confirm
      get :gallery
      get :gallery_list
    end
    member do
      patch :confirm
    end
  end
  resources :pictures do
    collection do
      post :confirm
      patch :confirm
    end
    member do
      patch :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :content, presence: true, length: {minimum:1, maximum:50}
  mount_uploader :post_image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name, presence: true, length: { in: 1..20 }
  validates :email, length: { in: 1..50 }, 
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :email, uniqueness: true
  validates :email, presence: true, allow_blank: true, on: :update
  validates :email, presence: true, allow_blank: true, on: :edit_case
  validates :password, length: { minimum: 6 }, on: :create
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true, on: :update
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true, on: :edit_case
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to picture_path(params[:picture_id]), notice: "お気に入りに登録しました"
  end
  
  def destroy   
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to request.referer, notice: "お気に入り解除しました" || pictures_path 
  end
end

app/controllers/picture_controller.rb
class PictureController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:edit, :show, :update,:destroy]
  before_action :ensure_current_user, only: [:edit, :update]

  def index
    @pictures = Picture.all
    if params[:name] == "asc"
      @pictures = @pictures.order(id: :asc)
    elsif params[:name] == "desc"
      @pictures = @pictures.order(id: :desc)
    elsif params[:name] == "with_image"
      @pictures = @pictures.where.not(post_image: nil)
    end  
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def confirm
    @picture =  Picture.new(picture_params)
    @picture.id = params[:id]
    @picture.user_id = current_user.id
    if @picture.id?
      render :edit and return if @picture.invalid?
    else
      render :new if @picture.invalid?
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        # PictureMailer.picture_mail(@picture).deliver 
        redirect_to pictures_path, notice: "投稿しました"
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
  end
  
  def update
    if params[:back]
      render :edit
    else
      if @picture.update(picture_params)
        redirect_to picture_path(@picture.id), notice: "編集しました"
      else
        render :edit
      end
    end
  end

  def destroy
    
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "投稿を削除しました！"
  end

  private
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:content, :id, :post_image, :post_image_cache, :image, :image_cache)
  end
  def ensure_current_user
    if @current_user.id != @picture.user_id
      redirect_to pictures_path, notice: "権限がありません"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id), success: 'ログインしました'  
    else
      flash[:notice] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    session.delete(:user_id)
    redirect_to new_session_path, success: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destroy]
  skip_before_action :login_required, only: [:new, :create, :confirm]
  before_action :ensure_current_user, only: [:edit, :update, :destroy]

  def new
    if params[:back]
      @user = User.new(user_params)
    else
      @user = User.new
    end
  end
  
  def confirm
    @user = params[:id] ? User.find(params[:id]) : User.new(user_params)
    if @user.id?
      @user.assign_attributes(user_params)
      render :edit and return if @user.invalid?(:edit_case)
    else
      @user.id =  params[:id] ? params[:id] : nil
      render :new if @user.invalid?
    end
  end

  def create
    @user = User.new(user_params)
    if params[:back]
      render :new
    else
      if @user.save
        redirect_to user_path(@user.id), notice: "ユーザー登録完了しました！"
      else
        render :new
      end
    end
  end

  def show
  
  end

  def edit
  end

  def update
    if params[:back]
      render :edit
    else
      if @user.update(user_params)
        redirect_to user_path(@user.id), notice: "プロフィール編集しました！"
      else
        render :edit
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to new_user_path, notice: "ご利用ありがとうございました！登録情報を削除しました！"
  end

  def gallery
    @user = current_user
    favorites = Favorite.where(user_id: current_user.id).pluck(:picture_id)
    @favorite_list = Picture.find(favorites) 
  end
  
  def gallery_list
    @user = current_user
    favorites = Favorite.where(user_id: current_user.id).pluck(:picture_id)
    @favorite_list = Picture.find(favorites) 
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:id, :name, :email, :image, :image_cache, :password, :password_confirmation)
  end

  def ensure_current_user
    if current_user.id != @user.id
      redirect_to user_path(current_user.id), warning: "権限がありません"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def confirm_action_picture
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit' || action_name == 'update'
      confirm_picture_path
    end
  end
  def confirm_id_picture
    unless @picture.id?
      pictures_path
    else
      picture_path
    end
  end
  def confirm_request_picture
    @picture.id ? 'patch' : 'post'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def confirm_action
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_users_path
    elsif action_name == 'edit' || action_name == 'update'
      confirm_user_path
    end
  end
  def confirm_id
    unless @user.id?
      users_path
    else
      user_path
    end
  end
  def confirm_request
    @user.id ? 'patch' : 'post'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photodia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class='body_wrapper'>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Photodia</a>
          </div>
          <% if logged_in? %>  
            <ul class="nav navbar-nav">
              <li><%= link_to "投稿一覧", pictures_path %></li>
              <li><%= link_to "投稿", new_picture_path %></li>
              <li><%= link_to "お気に入り", gallery_users_path %></li>
              <li><%= link_to "ギャラリー", gallery_list_users_path %></li>
              <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to session_path(current_user.id), { method: :delete, data: {confirm: "ログアウトしますか？"}} do %>
                  Logout
                <% end %>
              </li>
            </ul>
            <% else %>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to new_session_path, class: 'post' do %>
                    Login
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_path, class: 'post' do %>
                    SignUp
                  <% end %>
                </li>
              </ul>
          <% end %>
        </div>
      </nav>
      <div class="flash_message">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key} bg-success") %>
        <% end %>
      </div>
      <%= yield %>
      <footer>
        <div class='footer'>
          <p class='copyright'>ssss</p>
        </div>
      </footer>
    </div>   
  </body>
</html>

app/views/pictures/_form.html.erb
<% if @picture.errors.any? %>
  <div id="error_explanation">
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @picture.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @picture, local: true ,url: confirm_action_picture) do |f| %>
  <div class="contents_wrapper float">
    <div class="float_column">
      <div class="content_area">
        <div class="comment_area">
          <p class="comment_label left_margin"><%= f.label :'コメント' %></p>
          <%= f.text_area :content, class: 'comment left_margin' %>
        </div>
        <div class="image_area_picture">
          <%= f.file_field :post_image %>
          <%= image_tag(@picture.post_image.url) if @picture.post_image && @picture.post_image.url %>
          <%= f.hidden_field :post_image_cache %>
        </div>
      </div>
      <div>
        <%= f.submit "入力内容確認", class: "btn btn-warning side_margin" %>
        <%= link_to "一覧に戻る", pictures_path, class: "btn btn-warning side_margin" %>
      </div>
      <%= f.hidden_field :user %>
    </div>    
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<div class='page_title bottom_margin'>
  <h3>内容確認</h3>
</div>
<%= form_with(model: @picture, local: true ,url: confirm_id_picture, method: confirm_request_picture) do |f| %>
  <div class="contents_wrapper">
    <div class='contents_container'>
      <% if @picture.user.image.thumb.url %>
        <div class="container_image">
          <%= image_tag @picture.user.image.thumb.url %>
        </div>
      <% else %>
        <div class="non_image">
          <p>non_image</p>
        </div>
      <% end %>
      <div class="container_remove_image">
        <div class="container_name">
          <p> 名前 : <%= @picture.user.name %></p>
        </div>
        <div class="container_comment">
          <div class="overflow-wrap top_padding"> コメント：<%= (@picture.content) %></div>
          <%= f.hidden_field :content %>
        </div>
        <div class="picture_container bottom_padding">
          <div class="picture_content">
            <p class="picture_tag">
              <% if !@picture.post_image.url %>
                <p class="picture_tag">picture : 変更なし</p>
              <% else %>
                <p class="picture_tag">picture</p>
              <% end %>
            </p>
            <%= f.hidden_field :post_image_cache %>
            <%= f.hidden_field :post_image %>
            <%= image_tag(@picture.post_image.url) if @picture.post_image && @picture.post_image.url %>
          </div>
          <div class="bottom_padding">
            <% if @picture.id %>
              <p>投稿番号 : <%= @picture.id %></p> 
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="float">
      <%= f.submit "送信", class: "btn btn-warning side_margin" %>
      <%= f.submit "戻る", class: "btn btn-warning side_margin", name: 'back' %>
      <%= link_to "一覧に戻る", pictures_path, class: "btn btn-warning side_margin" %>
    </div>
    <%= f.hidden_field :user %>
  </div>
<% end %>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/edit.html.erb
<div class="main_wrapper">
  <div class='page_title'>
    <h3>編集</h3>
  </div>
  <%= render 'form' %>
</div>

app/views/pictures/index.html.erb
<div class="main_wrapper">
  <div class="title_wrapper">
    <div>
      <div class='page_title'>
      <h3>投稿一覧ページ</h3>
    </div>
    <div class="contents_wrapper">
      <% @pictures.each do |p| %>
        <div class='contents_container'>
          <% if p.user.image.thumb.url %>
            <div class="container_image">
              <%= image_tag p.user.image.thumb.url %>
            </div>
          <% else %>
            <div class="non_image">
              <p>non_image</p>
            </div>
          <% end %>
          <div class="container_remove_image">
            <div class="container_name">
              <p> 名前 ： <%= p.user.name %></p>
            </div>
            <%= content_tag(:div, content_tag(:div, "コメント：#{p.content}", class: "overflow-wrap"), class: "container_comment #{'container_comment_without_image' if !p.post_image.url}") %>
            <div class="picture_container bottom_padding">
              <div class="picture_img_area">
                <% if p.post_image.url %> 
                  <p class="picture_tag">picture</p>
                  <%= image_tag p.post_image.url, class: "picture" if p.post_image? %>
                <% end %>
              </div>
              <%= content_tag(:div, content_tag(:p, p.created_at.strftime("%Y-%m-%d %H:%M")), class: "container_day #{'without_image' if !p.post_image.url}") %>
            </div>
            <div class="button_container">
              <%= link_to "詳細", picture_path(p.id), class: "select_button" %>
              <% if p.user == current_user %>
                <%= link_to "編集", edit_picture_path(p.id), class: "select_button" %>
                <%= link_to "削除", picture_path(p.id), method: :delete, data: { confirm: '本当に削除しますか？'}, class: "select_button" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %> 
    </div>
  </div>
</div>
<%= link_to "投稿する", new_picture_path, class: "button_low button_top" %>
<% if params[:name] == "desc" %>
  <%= link_to "昇順にする", pictures_path(name: 'asc'), class: "button_low button_middle" %>
<% else %>
  <%= link_to "降順にする", pictures_path(name: 'desc'), class: "button_low button_middle" %>
<% end %>
<%= link_to "画像付のみ", pictures_path(name: 'with_image'), class: "button_low" %>

app/views/pictures/new.html.erb
<div class="main_wrapper">
  <div class='page_title'>
    <h3>投稿</h3>
  </div>
  <%= render 'form' %>
</div>

app/views/pictures/show.html.erb
<div class='page_title bottom_margin'>
  <h3>投稿詳細</h3>
</div>
<div class="contents_wrapper">
  <div class='contents_container'>
    <div class="container_image">
      <% if @picture.user.image.thumb.url %>
        <%= image_tag @picture.user.image.thumb.url %>
      <% else %>
        <div class="non_image">
          <p>non_image</p>
        </div>
      <% end %>
    </div>
    <div class="container_remove_image">
      <div class="container_name">
        <p> 名前 : <%= @picture.user.name %></p>
      </div>
      <div class="container_comment">
        <div class="overflow-wrap"> コメント : <%= @picture.content %></div>
      </div>
      <div class="picture_container">
        <div>
          <% if @picture.post_image.url %> 
            <p class="picture_tag">picture</p>
            <%= image_tag @picture.post_image.url, class: "picture bottom_padding" if @picture.post_image? %>
          <% end %>
        </div>
        <div class="bottom_padding">
          <% unless @picture.user_id == current_user.id %>
            <% if @favorite.present? %>
              <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-warning' %>
            <% else %>
              <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-warning' %>
            <% end %>
          <% end %>
          <p><%= @picture.created_at.strftime("%Y-%m-%d %H:%M") %></p>
      </div>
      </div>
    </div>
  </div>
  <div class="float">
    <%= link_to "一覧に戻る", pictures_path, class: "btn btn-warning side_margin" %>
      <% if @picture.user_id == @current_user.id %>
        <%= link_to "編集", edit_picture_path(@picture.id), class: "btn btn-warning side_margin" %>
        <%= link_to "削除", picture_path(@picture.id), method: :delete, data: { confirm: '本当に削除しますか？'}, class: "btn btn-warning side_margin" %>
      <% end %>
  </div>
</div>

app/views/pictures/update.html.erb
<h1>Pictures#update</h1>
<p>Find me in app/views/pictures/update.html.erb</p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true, url:confirm_action) do |f| %>
  <div class='add_profile_layout'>
    <div class="table_wrapper slide_left">
      <table>
        <tbody>
          <tr>
            <td><%= f.label :"名前" %></td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td><%= f.label :"メールアドレス" %></td>
            <td><%= f.email_field :email %></td>
          </tr>
          <tr>
            <td><%= f.label :"パスワード"%></td>
            <td><%= f.password_field :password %></td>
          </tr>
          <tr>
            <td><%= f.label :"パスワード確認用" %></td>
            <td><%= f.password_field :password_confirmation %></td>
          </tr>
        </tbody>
      </table>
      <div>
        <%= f.submit "入力内容確認", class: "btn btn-warning #{'side_margin' if @user.id?} #{'button_middle' if !@user.id?}" %>
        <% if @user.id? %>
          <%= link_to '戻る', user_path(@user.id), class: "btn btn-warning side_margin" %>
        <% end %>
      </div>
    </div>
    <% if @user.id? %>
      <div class='slide_light'>
        <div class="image_area">
          <p>プロフィール画像</p>
          <%= f.file_field :image %>
          <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
          <%= f.hidden_field :image_cache %>
        </div>
      </div>
    <% end %>
  </div>  
<% end %>

app/views/users/confirm.html.erb
<div class="main_wrapper">
  <div class='page_title'>
    <h3>入力内容確認</h3>
  </div>
  <%= form_with(model: @user, local: true, url: confirm_id, method: confirm_request) do |f| %>
    <div class='add_profile_layout'>
      <div class="table_wrapper slide_left">
        <table>
          <tbody>
            <tr>
              <td><p>名前:</p></td>
              <td><p><%= @user.name %></p></td>
            </tr>
              <td><p>メールアドレス:</p></td>
              <td><p><%= @user.email %></p></td>
            <tr>
            </tr>
              <td><p>パスワード : </p></td>
              <td><p>＊＊＊＊＊＊＊＊</p></td>
            <tr>
            </tr>
              <td><p>パスワード確認用 : </p></td>
              <td><p>＊＊＊＊＊＊＊＊</p></td>
            <tr>
          </tbody>
        </table>
        <div>
          <% if @user.id? %>
            <%= f.submit "編集する", class: "btn btn-warning side_margin" %>
          <% else %>
            <%= f.submit "登録する", class: "btn btn-warning side_margin" %>
          <% end %>
          <%= f.submit "戻る", name: 'back', class: "btn btn-warning side_margin" %>
        </div>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :password %>
        <%= f.hidden_field :password_confirmation %>
      </div>
      <% if @user.id? %>
        <div class='slide_light'>
          <p>プロフィール画像</p>
          <% if @user.image? %>
            <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
            <%= f.hidden_field :image_cache %>
          <% else %>
            <div class='non_image'>
              <p>profile_image</p>
              <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
              <%= f.hidden_field :image_cache %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="main_wrapper">
  <div class='page_title'>
    <h3>プロフィール編集</h3>
  </div>
  <%= render 'form' %>
</div>

app/views/users/gallery.html.erb
<div class="main_wrapper">
  <div class="title_wrapper">
    <div>
      <div class='page_title'>
      <h3>お気に入り一覧</h3>
    </div>
    <div class="contents_wrapper">
      <% @favorite_list.each do |p| %>
        <div class='contents_container'>
          <% if p.user.image.thumb.url %>
            <div class="container_image">
              <%= image_tag p.user.image.thumb.url %>
            </div>
          <% else %>
            <div class="non_image">
              <p>non_image</p>
            </div>
          <% end %>
          <div class="container_remove_image">
            <div class="container_name">
              <p> 名前 : <%= p.user.name %></p>
            </div>
            <div class="container_comment">
              <div class="overflow-wrap"> コメント : <%= p.content %></div>
            </div>
            <div class="picture_container bottom_padding">
              <div>
                <% if p.post_image.url %> 
                  <p class="picture_tag">picture</p>
                  <%= image_tag p.post_image.url, class: "picture" if p.post_image? %>
                <% end %>
              </div>
              <div class="comment_box">
                <p><%= p.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              </div>
            </div>
            <div class="button_container">
              <%= link_to "詳細", picture_path(p.id), class: "select_button" %>
              <% if p.user == current_user %>
                <%= link_to "編集", edit_picture_path(p.id), class: "select_button" %>
                <%= link_to "削除", picture_path(p.id), method: :delete, data: { confirm: '本当に削除しますか？'}, class: "select_button" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %> 
    </div>
  </div>
</div>
<%= link_to "戻る", user_path(current_user.id), class: "button_low" %>

app/views/users/gallery_list.html.erb
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>	
  <script type="text/javascript">
    $(document).ready(function(){
      $('.slider').bxSlider({
          mode: 'fade',
          auto: true,
          slideWidth: 600,
          pause: 6000,
          auto: true,
          randomStart: true,
          autoHover: true,
          autoControls: true
      });
    });
  </script>
</head>
<div class="main_wrapper">
  <div class="float">
    <div class="gallery_wrapper">
      <div>
        <div class='page_title'>
          <h3>ギャラリー</h3>
        </div>
      </div>
      <div class="gallery_container">
        <ul class="slider">
          <% @favorite_list.each do |p| %>
            <% if p.post_image.url %>
                <li><%= image_tag p.post_image.url, class: "picture" if p.post_image? %></li>
            <% end %>
          <% end %> 
        </ul>
      </div>
    </div>
</div>
<%= link_to "戻る", user_path(current_user.id), class: "button_low" %>

app/views/users/new.html.erb
<div class="main_wrapper">
  <div class='page_title'>
    <h3>サインアップ</h3>
  </div>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="main_wrapper">
  <div>
    <h3 class='page_title'>プロフィール</h3>
  </div>
  <div class='add_profile_layout'>
    <div class="table_wrapper slide_left">
      <table>
        <tbody>
          <tr>
            <td><p>名前:</p></td>
            <td><p><%= @user.name %></p></td>
          </tr>
          <tr>
            <td><p>メールアドレス:</p></td>
            <td><p><%= @user.email %></p></td>
          </tr>
          <tr>
            <td><p>パスワード : </p></td>
            <td><p>＊＊＊＊＊＊＊＊</p></td>
          </tr>
          <tr>
            <td><p>パスワード確認用 : </p></td>
            <td><p>＊＊＊＊＊＊＊＊</p></td>
          </tr>
        </tbody>
      </table>
      <div class='button_area'>
        <% if current_user.id == @user.id %>
          <%= link_to "お気に入り", gallery_users_path, class: "btn btn-warning side_margin" %>
          <%= link_to "投稿", new_picture_path, class: "btn btn-warning side_margin" %>
          <%= link_to "編集", edit_user_path(@user.id), class: "btn btn-warning side_margin" %>
          <%= link_to '退会', user_path(@user.id), method: :delete, data: { confirm: '本当に退会しますか？'}, class: "btn btn-warning side_margin" %>
        <% end %>
      </div>
    </div>
    <div class='slide_light'>
      <div class="image_area">
        <p>プロフィール画像</p>
        <% if @user.image? %>
          <%= image_tag @user.image.url %>
        <% end %>
      </div>
    </div>
  </div>
</div> 